In [1]:
pip install pandas numpy mlxtend

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (1.26.4)
Collecting mlxtend
  Downloading mlxtend-0.23.4-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: scipy>=1.2.1 in c:\programdata\anaconda3\lib\site-packages (from mlxtend) (1.13.1)
Requirement already satisfied: scikit-learn>=1.3.1 in c:\programdata\anaconda3\lib\site-packages (from mlxtend) (1.4.2)
Requirement already satisfied: matplotlib>=3.0.0 in c:\programdata\anaconda3\lib\site-packages (from mlxtend) (3.8.4)
Requirement already satisfied: joblib>=0.13.2 in c:\programdata\anaconda3\lib\site-packages (from mlxtend) (1.4.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (23.2)
Requirement already satisfied: pillow>=8 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (10.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (3.0.9)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn>=1.3.1->mlxtend) (2.2.0)
Downloading mlxtend-0.23.4-py3-none-any.whl (1.4 MB)
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
    --------------------------------------- 0.0/1.4 MB 162.5 kB/s eta 0:00:09
   - -------------------------------------- 0.0/1.4 MB 279.3 kB/s eta 0:00:05
   --- ------------------------------------ 0.1/1.4 MB 587.0 kB/s eta 0:00:03
   -------- ------------------------------- 0.3/1.4 MB 1.5 MB/s eta 0:00:01
   ------------------ --------------------- 0.6/1.4 MB 2.6 MB/s eta 0:00:01
   ------------------------------ --------- 1.0/1.4 MB 3.8 MB/s eta 0:00:01
   ---------------------------------------  1.4/1.4 MB 4.5 MB/s eta 0:00:01
   ---------------------------------------- 1.4/1.4 MB 4.3 MB/s eta 0:00:00
Installing collected packages: mlxtend
Successfully installed mlxtend-0.23.4
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

In [4]:
file_path = r"C:\Users\Chetan\Downloads\ml-latest-small\ml-latest-small\ratings.csv"
df = pd.read_csv(file_path)

# Display the first few rows
df.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [5]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   userId     100836 non-null  int64
 1   movieId    100836 non-null  int64
 2   rating     100836 non-null  float64
 3   timestamp  100836 non-null  int64
dtypes: float64(1), int64(3)
memory usage: 3.1 MB

              userId        movieId         rating     timestamp
count  100836.000000  100836.000000  100836.000000  1.008360e+05
mean      326.127564   19435.295718       3.501557  1.205946e+09
std       182.618491   35530.987199       1.042529  2.162610e+08
min         1.000000       1.000000       0.500000  8.281246e+08
25%       177.000000    1199.000000       3.000000  1.019124e+09
50%       325.000000    2991.000000       3.500000  1.186087e+09
75%       477.000000    8122.000000       4.000000  1.435994e+09
max       610.000000  193609.000000       5.000000  1.537799e+09

#  Basic Apriori Algorithm

In [ ]:
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules

# Load the MovieLens dataset
file_path = r"C:\Users\Chetan\Downloads\ml-latest-small\ml-latest-small\ratings.csv"
df = pd.read_csv(file_path)

# Convert ratings into a binary format (liked/disliked)
df['liked'] = df['rating'].apply(lambda x: x >= 3.5)


# Create a pivot table for transactions (users as rows, movies as columns)
basket = df.pivot_table(index='userId', columns='movieId', values='liked', fill_value=False).astype(bool)

# Apply the Apriori algorithm
frequent_itemsets = apriori(basket, min_support=0.05, use_colnames=True, low_memory=True)

# Generate association rules
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1.0)

# Display the first few association rules
print(rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']].head())

# Improved Apriori (FP-Growth Algorithm)

In [ ]:
from mlxtend.frequent_patterns import fpgrowth

# Apply the FP-Growth algorithm (Improved Apriori)
frequent_itemsets_fpgrowth = fpgrowth(basket, min_support=0.05, use_colnames=True)

# Generate association rules for FP-Growth
rules_fpgrowth = association_rules(frequent_itemsets_fpgrowth, metric="lift", min_threshold=1.0)

# Display the first few association rules
print(rules_fpgrowth[['antecedents', 'consequents', 'support', 'confidence', 'lift']].head())